---
title: "Homologias, Caracteres e Mensurações"
subtitle: "Modularidade: conectando padrões e processos em evolução multivariada"
author: Guilherme Garcia
date: wgar@usp.br
logo: ../../logo.png
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage[brazilian]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage[bitstream-charter]{mathdesign}
  - \usepackage{setspace}
  - \doublespacing
fontsize: 12pt
csl: /home/guilherme/Dropbox/Global/nature.csl
bibliography: /home/guilherme/Dropbox/Global/CursoMod.bib
---	

Homologias são relações de equivalência entre atributos em espécies distintas.
Por exemplo, os membros anteriores de todos os Tetrapoda exibem similaridades estruturais que permitem inferir a existência de homologias em todo o grupo, ilustrada aqui pelas asas de morcegos, pterossauros e aves.
Aqui, vale a pena destacar três aspectos importantes deste conceito.
Em primeiro lugar, homologias entre atributos indicam origens evolutivas em comum entre estas linhagens, a despeito de modificações posteriores associadas aos hábitos destes organismos; no exemplo, há uma convergência funcional posterior relacionada ao voo.
Homologias também indicam a existência de vias de desenvolvimento em comum entre estas linhagens, ainda que esta correspondência seja apenas parcial, devido à modificações posteriores produzida pela evolução independente de linhagens filhas.
Finalmente, implica dos aspectos anteriores que homologias são relações globais entre estes atributos; ou seja, de modo a caracterizar uma relação de homologia entre espécies, a princípio não é necessário estabelecer uma correspondência unívoca entre partes da estrutura em questão.
No exemplo, ainda que consideremos esta estrutura homóloga como um todo, podemos observar (ou talvez lembrar) que as asas em Aves são caracterizadas por perdas e fusões entre ossos na porção distal do membro.

Em um exemplo mais extremo deste aspecto, ainda que os membros anteriores em Tetrapoda sejam homólogos aos membros anteriores em outras linhagens basais de Vertebrata, não há uma correspondência clara entre os elementos componentes destas estruturas.
Aqui podemos apenas estabelecer correspondências entre os *loci* envolvidos nestas vias de desenvolvimento compartilhadas por estas linhagens.
Neste exemplo, a fase inicial do desenvolvimento ósseo de membros anteriores em teleósteos, em sarcopterígios basais e em tetrápodes é determinada pela expressão dos mesmos três *loci*, enquanto as estruturas adicionais observadas nas linhagens mais derivadas é contingente à expressão destes mesmos três *loci* em fases posteriores do desenvolvimento [@yano_making_2013].

Podemos então pensar no mapa genótipo-fenótipo associado a uma dada estrutura morfológica em duas espécies distintas.
Assim, em uma espécie $i$, os *loci* 1 a 4 condicionam os caracteres A a D; este complexo de caracteres representam um módulo funcional, visto que estes caracteres executam em conjunto a função denotada por $\alpha$.
Como assumimos que as vias de desenvolvimento destes caracteres é relativamente independente de outros *loci* (não representados aqui), este também é um módulo ontogenético.
Em uma outra espécie $j$, os *loci* 3 e 4 passam por modificações (tornando se os loci 3' e 4') de tal forma que sua expressão durante o desenvolvimento levam a alterações nos caracteres A e C (agora A' e C') e também à ausência do caráter B.
Neste exemplo, podemos supor que estas modificações são consequência de seleção direcional ou estabilizadora relacionada a uma nova demanda funcional sobre estes caracteres, representada aqui como $\alpha'$.
O exemplo parece sugerir que homologias podem ser concebidas em qualquer escala de organização biológica.
Podemos portanto definir homologias entre estruturas morfológicas (entre A e A' ou C e C') e também entre sequências no genoma de organismos distintos, como estes *loci* individuais.

Nossa habilidade de reconhecer homologias em uma estrutura particular em escalas distintas depende da relação entre partes e todo naquela estrutura em particular.
No caso dos membros anteriores em mamíferos, é possível observar relações em comum entre as partes.
Desta forma, cada elemento ósseo individual em uma dada linhagem pode ser mapeado aos elementos em outras linhagens por suas relações de posição relativa.
Este refinamento nos permite definir caracteres homólogos com base em atributos destes elementos individuais, como por exemplo o comprimento de cada osso.

Aqui, vale a pena elaborar uma definição de caráter, e de modo geral, caracteres são conjuntos de atributos mutuamente exclusivos identificados em um dado conjunto de organismos. 
Por mutuamente exclusivos, me refiro ao fato de que em cada organismo, eu identifico apenas um estado do caráter em questão.
Por exemplo, neste conjunto de lagartos de colorações distintas, eu posso atribuir a cada um deles um estado distinto deste caráter "cor".
Note que cada organismo no conjunto é associados a apenas um estado do caráter, e que todos os organismos são associados a algum estado.
Obviamente, posso atribuir o mesmo estado a organismos que o compartilharem.
Esta definição, bastante geral, não impõe nenhuma restrição ao conjunto de atributos, que pode portanto ser de qualquer natureza.
Posso representar estes atributos em uma escala nominal como essa, mas posso também atribuir a cada organismo um conjunto de três valores, que aqui representam a decomposição da cor de cada organismo em vermelho, verde e azul.
Esta definição também não impõe restrições a respeito do agrupamento do conjunto de organismos: estes lagartos podem representar uma população da mesma espécie, ou espécies distintas dentro de um gênero, ou até mesmo gêneros e famílias distintas, independente também das relações evolutivas entre estas unidades (por exemplo, se estas espécies formam ou não agrupamentos monofiléticos).

É importante notar que, a princípio, esta definição de caráter não faz referência a homologias.
De uma certa maneira, a partir desta definição, caracteres são divisões arbitrárias que somos capazes de reconhecer em organismos, ou em partes destes organismos.
No exemplo dos lagartos, a princípio não sabemos se as colorações distintas são produzidas por vias metabólicas ou ontogenéticas em comum; apenas somos capazes de reconhecer diferenças neste atributo, e também somos capazes de dar a cada estado deste atributo uma denominação distinta.
O que determina a utilidade um conjunto de caracteres para representar um dado organismo ou suas partes é o contexto téorico de referência, ou seja, as relações que estabelecemos entre um fenômeno de interesse e os efeitos deste fenômeno sobre organismos de interesse, representados sob a forma de caracteres em que esperamos que estes efeitos sejam mensuráveis.
Acredito que um exemplo [@levins_dialectical_1985; @houle_measurement_2011] deve deixar isso mais claro.

Neste exemplo, consideramos a relação entre tolerância térmica e coloração em lagartos.
Assim, esta tolerância térmica depende de uma série de fatores, entre eles coloração e a relação entre superfície e volume nos indivíduos de uma população; estes fatores se relacionam à tolerância térmica dos organismos considerando seus efeitos sobre a dissipação e absorção de calor.
Vamos ignorar neste exemplo o efeito de forma sobre a tolerância térmica, supondo que a variação neste caráter é pequena o bastante para ser desprezada.
Desta forma, estes lagartos variam em coloração, e novamente, não temos a princípio a menor ideia de como esta variação em coloração é expressa em termos de produtos de vias de desenvolvimento.
Uma maneira de relacionar esta coloração à tolerância térmica se dá através de um experimento que consiste em separar os lagartos em diferentes tratamentos de acordo com sua coloração e aumentar a temperatura gradativamente de modo que registramos a temperatura em que metade dos indivíduos em cada tratamento acabam por morrer.
Este atributo representa a tolerância térmica associada a cada coloração na população e, por exemplo, podemos supor que indivíduos com colorações mais próximas de marrom possuem tolerâncias térmicas maiores conforme a ordenação do atributo mensurado.
Esta ordenação representa a estrutura de relações empíricas associada ao atributo $T_{50}$, que se refere ao conjunto de organismos, as operações que podemos executar com eles (por exemplo, agrupá-los em função de suas cor e cozinhá-los lentamente) e as relações estabelecidas a partir destas operações (no caso, quem morre mais rápido).
Conforme a hipótese, a variação em quem morre mais rápido de fato se associa à variação em coloração na população.

Mas então porque medir caracteres homólogos?
Ora, se é do nosso interesse fazer inferências a respeito da estrutura do mapa genótipo-fenótipo em um complexo morfológico em espécies distintas, é necessário que a estrutura das relações empíricas entre os caracteres que definimos respeite as relações de homologia entre partes nestas espécies.
Somente desta forma podemos conectar os efeitos observados nestes caracteres (como por exemplo sua estrutura de covariância) às diferenças ou similaridades em processos estruturadores do desenvolvimento (como a rede de interações pleiotrópicas).

Isto significa que é imperativo medir caracteres homólogos?
Claro que não.
Em resumo, isto depende de qual contexto teórico queremos utilizar como referência.
No caso de uma comparação entre estas linhagens distintas de vertebrados, talvez gostaríamos de avaliar se a convergência funcional entre estruturas produz covariâncias similares entre elementos que executam funções análogas, a despeito de suas origens ontogenéticas.
Neste caso, apenas temos que atentar para o fato de que os caracteres que vamos definir neste contexto serão bastante diferentes do que aqueles que definimos no contexto de homologias.
No exemplo, provavelmente deveríamos mensurar a área de cada nadadeira, o formato do contorno exterior e provavelmente algo relacionado à musculatura propulsora de cada nadadeira, por exemplo.



## Bibliografia
